### ISSUE TITLE
Overview the Schedule

### ISSUE THREAD

**Issue by annagabain** [annagabain/Mom-Schedule#1]
### User Story: 
  
As **user** I can **look at the Schedule** so that **I can overview my tasks**

  
### Acceptance Criteria:
  
- [x] The schedule is displayed correctly
- [x] Individual Tasks can be clicked on
- [x] Chosen Task is displayed

### Tasks
 
- [x] List all the tasks
- [x] Make sure they are ordered according to the date

**Comment by annagabain** [comment]
user story template
