### ISSUE TITLE
Sidebar

### ISSUE THREAD

**Issue by annagabain** [annagabain/Mom-Schedule#11]
### User Story: 
  
As **user** I can **see a sidebar** so that **I sort my tasks and manage them**
As **a user**, I can **see a navigation option** (sidebar) so that I can **sort my tasks, manage them, as well as find the contact option**
  
### Acceptance Criteria:
  
- [x] The sidebar is self explanatory and intuitive to use

### Tasks
 
- [x] Create a side bar
- [x] Add Filter_by feature
- [x] Add Create a new task circle button
