### ISSUE TITLE
Account authorisation - User - Register

### ISSUE THREAD

**Issue by annagabain** [annagabain/Mom-Schedule#5]
### User Story: 
 
As a **site user** I can **register** so that **I can have a unique and private schedule**
  
### Acceptance Criteria:
  
- [x] The user is visible in the admin panel
- [x] The user is notified about the successful registration
- [x] The user is redirected to the Schedule overview page

### Tasks
 
- [x] Compete the user registration form
- [x] Make a Bootstrap success message that is displayed to the user
- [x] Redirect to the Schedule page

**Comment by annagabain** [comment]
Bootstrap messages: https://ordinarycoders.com/blog/article/django-messages-framework
